version: '3.8'
services:
  service-doctor:
    ports:
      - 6060:6060
    image: service-doctor-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "TZ=Europe/Rome"
    container_name: service-doctor
    networks:
      - net_storage

networks:
  net_storage:
    name: net_storage
    external: true